- hosts: localhost
  connection: local

  roles:
    - packer
    - docker-compose
    - golang

  tasks:
    - name: install debootstrap
      apt: name=debootstrap

    - name: install screen
      apt: name=screen

    - name: install ipcalc
      apt: name=ipcalc

    - name: install dnsutils
      apt: name=dnsutils

    - name: install curl
      apt: name=curl

    - name: install bc
      apt: name=bc
