- hosts: work
  connection: docker

  roles:
    - golang

  tasks:
    - name: install less
      apt:
        name: less

    - name: install vim
      apt:
        name: vim

    - name: install man
      apt:
        name: man-db

    - name: install locales
      apt:
        name: locales

    - name: debconf locales
      debconf:
        name: locales
        question: 'locales/locales_to_be_generated'
        value: 'ja_JP.UTF-8 UTF-8'
        vtype: 'multiselect'

    - name: generate locales
      lineinfile:
        dest: /etc/locale.gen
        regexp: '^# (ja_JP.UTF-8.*)$'
        line: '\1'
        backrefs: yes
      notify: locale-gen

    - name: install netbase
      apt:
        name: netbase

    - name: install whois
      apt:
        name: whois

    - name: install git
      apt:
        name: git

    - name: install iproute2
      apt:
        name: iproute2

    - name: install iputils-ping
      apt:
        name: iputils-ping

    - name: install netcat
      apt:
        name: netcat

  handlers:
    - name: locale-gen
      shell: /usr/sbin/locale-gen
