FROM local/debian-8.3.0-amd64
# http://iij.dl.osdn.jp/nhocr/61902/nhocr-0.22.tar.gz
# http://www.imglab.org/p/O2/archives/O2-dtools-2.00.tar.gz
# http://www.imglab.org/p/O2/archives/O2-tools-2.01.tar.gz
# RUN DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server-5.5
