- name: install unzip
  apt:
    name: unzip

- name: download packer
  get_url:
    url: 'https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip'
    dest: '/tmp/packer_{{ packer_version }}_linux_amd64.zip'
    checksum: '{{ packer_checksum }}'
  register: packer_tarball

- name: rmdir packer
  file:
    path: '{{ packer_install_dir }}'
    state: absent
  when: packer_tarball.changed

- name: stat packer dir
  stat:
    path: '{{ packer_install_dir }}'
  register: packer_dir

- name: mkdir packer
  file:
    path: '{{ packer_install_dir }}'
    state: directory
    mode: '2775'
    owner: root
    group: staff

- name: unarchive packer
  unarchive:
    src: '/tmp/packer_{{ packer_version }}_linux_amd64.zip'
    dest: '{{ packer_install_dir }}'
    copy: no
  when: packer_dir.stat.exists == False

- name: add packer path to bash
  copy:
    src: etc/profile.d/20packer.sh
    dest: /etc/profile.d/
    mode: '0644'
    owner: root
    group: root

- name: add packer path to sudo
  script: make_sudoers.sh
